# Generated by Django 3.2.5 on 2021-07-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('contents', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('cdate', models.CharField(max_length=200)),
            ],
        ),
    ]
